src/carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home,
    cart_update,
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

# from products.views import ( 
#     ProductListView,from products.views import ( 
#     ProductListView,
#     ProductDetailView,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
#     ProductDetailSlugView
#     )
#     ProductDetailView,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
#     ProductDetailSlugView
#     )
from carts.views import cart_home

from .views import home_page, about, contact, login_page, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^about/$', about, name='login'),
    url(r'^login/$', login_page, name='login'),
    url(r'^register/$', register_page, name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^search/', include('search.urls', namespace='search')),
   ]

#url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/search/urls.py
from django.conf.urls import url

from .views import (
        SearchProductView
        )

urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name='query'),
]   

src/search/models.py
from django.db import models

# Create your models here.

src/search/views.py
from django.shortcuts import render
from django.views.generic import ListView

from products.models import Product

class SearchProductView(ListView):
    template_name = 'search/view.html'

    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        # SearchQuery.objects.create(query=query)
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return Product.objects.filter(title__icontains=query)
        return Product.objects.none()

src/search/templates/search/snippets/search-form.html
{% comment %} <form method='GET' action='{% url "search:query" %}' class="form my-2 my-lg-0">
  <div class='input-group'>
    <input class="form-control" type="text" placeholder="Search" name='q' aria-label="Search" value='{{ request.GET.q }}'>
    <span class='input-group-btn'>
        <button class="btn btn-outline-success" type="submit">Search</button>
    </span>
    </div>
</form> {% endcomment %}

<form class="form-inline my-2 my-lg-0 ml-auto" method='GET' action='{% url "search:query" %}'>
  <div class="input-group add-on" id="search-div">
    <button id="search_button" class="btn btn-default" id="search_icon_btn" type="submit" data-etracking="true" data-ecategory="search"><i class="fa fa-search" aria-hidden="true"></i></button>
      <input id="search_bar" class="form-control" type="search" placeholder="E.g.:Batman tshirts" name='q' aria-label="Search" value='{{ request.GET.q }}'>
      <!-- <button class="btn btn-default" type="submit">Search</button> -->
  </div>
</form>