src/carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home,
    cart_update,
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

# from products.views import ( 
#     ProductListView,from products.views import ( 
#     ProductListView,
#     ProductDetailView,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
#     ProductDetailSlugView
#     )
#     ProductDetailView,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
#     ProductDetailSlugView
#     )
from carts.views import cart_home

from .views import home_page, about, contact, login_page, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^about/$', about, name='login'),
    url(r'^login/$', login_page, name='login'),
    url(r'^register/$', register_page, name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^search/', include('search.urls', namespace='search')),
   ]

#url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import (
        ProductListView, 
        ProductDetailSlugView, 
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]   

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

<!--Font awesome icon cdn-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href='{% static "css/main.css" %}'>

src/templates/base/footer.html
<section class="ending">
			<div class="container">
				<div class="row">
					<div class="col-md-2 end">
                        <div>Buyer Centeral</div>
						<ul>
							<li><a href="">Terms & conditons us</a></li>
							<li><a href="">Privacy Policy</a></li>
							<li><a href="">B2B Login</a></li>
						</ul>
                    </div>
                    
                    <div class="col-md-2 end">
                        <div>Help</div>
						<ul>
							<li><a href="">Shipping help</a></li>
							<li><a href="">Return Policy</a></li>
							<li><a href="">Wallet Policy</a></li>
						</ul>
                    </div>
                    
                    <div class="col-md-2 end">
                        <div>About Us</div>
						<ul>
							<li><a href="">About us</a></li>
							<li><a href="">Contact us</a></li>
						</ul>
                    </div>
                    
                    <div class="col-md-2 end">
                        <div>Our Stores</div>
						<ul>
							<li><a href="">Stores</a></li>
							<li><a href="">Become a Franchise</a></li>
						</ul>
					</div>
					
					<div class="col-md-4 social">
                            <div>Connect</div>
						<ul>
							<li><a href=""><i class="fa fa-facebook"></i></a></li>
							<li><a href=""><i class="fa fa-twitter"></i></a></li>
							<li><a href=""><i class="fa fa-google"></i></a></li>
							<li><a href=""><i class="fa fa-instagram"></i></a></li>
							<li><a href=""><i class="fa fa-whatsapp"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light ">
    
  <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{brand_name}} {% else %} Gifto {% endif%}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>

      {% if request.user.is_authenticated %}
       <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"> {{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>


<header>
        <!--NavBar-->
            <nav class="navbar navbar-expand-md fixed-top navbar-light navbar-dark bg-dark" id="custom-nav">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    {% include 'search/snippets/search-form.html' %}
                    <ul class="navbar-nav ml-auto" id="nav_lis">

                        <li class="nav-item nav_lis" id="offer_nav">
                            <a class="nav-link" href="#"><i class="fa fa-tag fa-lg"></i> OFFERS</a>
                        </li>

                        <li class="nav-item nav_lis {% if request.path == home_url %}active{% endif %}">
                          <a class="nav-link" href="{{ home_url }}"> <i class="fa fa-tag fa-lg"></i> Home <span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item nav_lis {% if request.path == product_list_url %}active{% endif %}">
                          <a class="nav-link" href="{{ product_list_url }}">Products</a>
                        </li>

                        <li class="nav-item nav_lis {% if request.path == contact_url %}active{% endif %}">
                          <a class="nav-link" href="{{ contact_url }}">Contact</a>
                        </li>

                        {% if request.user.is_authenticated %}
                        <li class="nav-item nav_lis {% if request.path == logout_url %}active{% endif %}">
                          <a class="nav-link" href="{{ logout_url }}">Logout</a>
                        </li>
                        {% else %}

                        <li class="nav-item nav_lis {% if request.path == register_url %}active{% endif %}">
                          <a class="nav-link" href="{{ register_url }}">Register</a>
                        </li>

                        <li class="nav-item nav_lis {% if request.path == login_url %}active{% endif %}">
                          <a class="nav-link" href="{{ login_url }}">Login</a>
                        </li>
                        {% endif %}

                        <li class="nav-item nav_lis {% if request.path == cart_url %}active{% endif %}">
                          <a class="nav-link" href="{{ cart_url }}"> {{ request.session.cart_items }} <i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i></a>
                        </li>


                    </ul>
                </div>
            </nav><!--End Of Nav Bar-->
      </header>