src/carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home,
    cart_update,
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

# from products.views import ( 
#     ProductListView,from products.views import ( 
#     ProductListView,
#     ProductDetailView,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
#     ProductDetailSlugView
#     )
#     ProductDetailView,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
#     ProductDetailSlugView
#     )
from carts.views import cart_home

from .views import home_page, about, contact, login_page, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^about/$', about, name='login'),
    url(r'^login/$', login_page, name='login'),
    url(r'^register/$', register_page, name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^search/', include('search.urls', namespace='search')),
   ]

#url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import (
        ProductListView, 
        ProductDetailSlugView, 
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]   

src/products/models.py
from django.db import models
import random, os
from django.db.models.signals import pre_save
from .util import unique_slug_generator
from django.urls import reverse
from django.db.models import Q
# Create your models here.
def get_filename_ext(filename):
    base_name = os.path.basename(filename)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    print(instance)
    print(filename)
    new_filename = random.randint(1, 399239998)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename= new_filename, ext=ext)
    return 'products/{new_filename}/{final_filename}'.format(new_filename= new_filename, final_filename=final_filename)

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True,  active=True)

    # def search(self, query):
    #     lookups = (Q(title__icontains=query) | 
    #               Q(description__icontains=query) |
    #               Q(price__icontains=query) |
    #               Q(tag__title__icontains=query)
    #               )
        # tshirt, t-shirt, t shirt, red, green, blue,
        # return self.filter(lookups).distinct()

class ProductManager(models.Manager):

    def featured(self): #Product.objects.featured() 
        return self.get_queryset().featured()

    def all(self):
        return self.get_queryset().active()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id= id)
        if qs.count() == 1:
            return qs.first()
        return None

    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    # def search(self, query):
    #     return self.get_queryset().active().search(query)


GENDER_CHOICES = (
    ('male', 'MALE'),
    ('female', 'FEMALE')
)

RELATION_CHOICES = {
    ('brother', 'BROTHER'),
    ('sister', 'SISTER'),
    ('mom', 'MOM'),
    ('dad', 'DAD'),
    ('mom', 'MOM'),
    ('friend', 'FRIEND'),
    ('girl friend', 'GIRL FRIEND'),
    ('boy friend', 'BOY FRIEND'),
    ('other', 'OTHER'),
}

RELATION_CHOICES = {
    ('brother', 'BROTHER'),
    ('sister', 'SISTER'),
    ('mom', 'MOM'),
    ('dad', 'DAD'),
    ('mom', 'MOM'),
    ('friend', 'FRIEND'),
    ('girl friend', 'GIRL FRIEND'),
    ('boy friend', 'BOY FRIEND'),
    ('other', 'OTHER'),
}

INTRESTS_CHOICES = {
    ('tech', 'TECH'),
    ('traveling', 'TRAVELLING'),
    ('reading', 'READING'),
    ('art', 'ART'),
    ('music', 'MUSIC'),
    ('sports', 'SPORTS'),
    ('painting', 'PAINTING'),
    ('other', 'OTHER'),
}

class Product(models.Model):
    title           = models.CharField(max_length= 100)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places = 2, max_digits= 10, default = 10) #null = True
    image           = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured        = models.BooleanField(default= False)
    active          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    minAge          = models.DecimalField(decimal_places=0, max_digits=100, default=5)
    maxAge          = models.DecimalField(decimal_places=0, max_digits=100, default=90)
    gender          = models.CharField(max_length=6, choices=GENDER_CHOICES, default='male')
    relation        = models.CharField(max_length=6, choices=RELATION_CHOICES, default='brother')
    intrests        = models.CharField(max_length=6, choices=INTRESTS_CHOICES, default='tech')
    occupation      = models.CharField(max_length=20, default='ALL')
    category        = models.CharField(max_length=20, default='ALL')
    

    objects = ProductManager()

    def get_absolute_url(self):
        # return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

src/products/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render

from carts.models import Cart
from .models import Product
# Create your views here.

class ProductFeaturedListView(ListView):
    template_name = 'products/list.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()

class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()   
    template_name = 'products/featured-detail.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.featured()    

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return Product.objects.filter(pk=pk)


class ProductListView(ListView):
    # queryset = Product.objects.all()
    template_name = 'products/list.html'

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     print(context)
    #     return context
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()

class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = 'products/detail.html'

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = Product.objects.get(slug=slug, active =True)
        except Product.DoesNotExist:
            raise Http404('Not FOund')
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active =True)
            instance = qs.first()
        except: 
            raise Http404('Something went worng')
        return instance

    
    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return Product.objects.filter(pk=pk)


class ProductDetailView(DetailView):
    # queryset = Product.objects.all()
    template_name = 'products/detail.html'

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
    #     print(context)

    def get_queryset(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        return Product.objects.filter(pk=pk)

    # def get_object(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     instance = Product.objects.get_by_id(pk)
    #     if instance is None:
    #         raise Http404("Product doesn't exist")
    #     return instance

src/products/templates/products/detail.html
{% extends "base.html" %}
{% load static%}
{% url './products:list' as product_list_url %}

{% block base_head%}
  <title> {{ object.title}} </title>
  <link rel="stylesheet" href='{% static "css/detail.css" %}'>
{% endblock %}

{% block content%}


<div class="container mt-4">
    <div class="row" >
        <div class="col-md-3">
            <div class="list-group">
                <li class="list-group-item active">Detail</li>
                <li class="list-group-item"><b>Name:</b> <i>{{ object.title}}</i></li>
                <li class="list-group-item"><b>Price:</b> <i>&#8377;{{ object.price}}</i></li>
                
                {% comment %} <a href="#"><li class="list-group-item">Go Back</li></a> {% endcomment %}
                <a href="http://127.0.0.1:8000/products/"><li class="list-group-item text-center">Go Back</li></a>
            </div>
        </div>
        <div class="col-md-9" >
            
            {% if object.image %}
                <img src='{{ object.image.url }}' class='img-fluid mb-3' />
            {% endif %}
            
            <div class="caption-full" >
                    <div class="pull-right">{% include 'products/snippets/update-cart.html' with product=object cart=cart %}</div>
                    <h3> {{ object.title}} </h3>
                    <p class='pb-1' id='time_ago'>{{ object.timestamp|timesince }} ago<p>
                            
            </div>

            <div id='description'>
                <h2 class="text-center"> &#8377;  {{ object.price}} </h2>
                <br />
                {{ object.description|linebreaks}} <br />
            </div>

        </div>
    </div>
</div>


{% endblock %}

src/products/templates/products/featured-detail.html
{{ object.title}} <br />

{{ object.description}} <br />

{% if object.image %}
    <img src='{{ object.image.url }}' class='img-fluid' />
{% endif %}

src/products/templates/products/list.html
{% extends "base.html" %}

{% load static%}


{% block base_head%}
  <title> Products </title>
  <link rel="stylesheet" href='{% static "css/product_list.css" %}'>
{% endblock %}


{% block content %}
     <div class='container-fluid' id='list_div'>
           <div class='row'>
                <div class='col-md-2'></div>

                <div class='col-md-10'>
                
                    <div class='container'>
                    
                        <div class='row'>

                            {% for obj in object_list %}
                                <div class='col'>
                                {% include 'products/snippets/card.html' with instance=obj %}  
                                
                                {% if forloop.counter|divisibleby:3 %}
                                </div> </div><div class='row'><div class='col-12'><hr/></div>
                                {% comment %} {% elif forloop.counter|divisibleby:2 %}
                                    </div> </div><div class='row'><div class='col-12'><hr/></div> {% endcomment %}
                                {% else %}
                                </div>  
                                {% endif %}

                            {% endfor %}
                        </div>

                    </div>

                </div>
           </div>
     </div>
{% endblock %}